package by.bsuir.nika.lombard.controller.command.util;

public enum CommandName {

    GO_TO_ALL_CLIENTS_COMMAND,
    GO_TO_CLIENT_COMMAND,
    GO_TO_CREATE_CLIENT_COMMAND,
    GO_TO_UPDATE_CLIENT_COMMAND,
    CREATE_CLIENT_COMMAND,
    UPDATE_CLIENT_COMMAND,
    DELETE_CLIENT_COMMAND,
    GO_TO_ALL_ITEMS_COMMAND,
    GO_TO_ITEM_COMMAND,
    GO_TO_CREATE_ITEM_COMMAND,
    GO_TO_UPDATE_ITEM_COMMAND,
    CREATE_ITEM_COMMAND,
    UPDATE_ITEM_COMMAND,
    DELETE_ITEM_COMMAND,
    REALISE_ITEM_COMMAND,
    GO_TO_REPORT_COMMAND

}
